Feature/dashboard 03 August Dashboard with complete graphQL (bar feedback component)
Kubrick-Group/kubrick-cdp pull request #4
Opened 2021-08-03 17:27 UTC by EmmaBaldachin

Richard - review code in general and architecture
To review in particular:
In readNotification mutation - is the if statement at the beginning okay practise? should this be handled in the grandchild component so it only actually emits an event if it is not in the read state?
Is structure of code in asyncData okay? Or should we put all queries first then all data manipulation
Are my comments in the code okay? i.e should there be more & more detailed / less as they aren't needed.
Thanks

2021-08-03 23:33 UTC, monkemedia requested changes
Really good stuff Emma. Just some minor changes and questions.

2021-08-03 23:33 UTC, monkemedia commented on components/HomepageHero.vue
> +        default: () => ''
for strings you can just use:

```
default: ''
```

2021-08-03 23:33 UTC, monkemedia commented on components/HomepageHero.vue
> +        default: () => ''
As above ^

2021-08-03 23:33 UTC, monkemedia commented on graphql/mutations/readNotification.gql
> +}
Add an empty line below

2021-08-03 23:33 UTC, monkemedia commented on graphql/queries/getFeedback.gql
> +}
Add empty line below

2021-08-03 23:33 UTC, monkemedia commented on package.json
> +    "@kubrick/kubrickui": "^0.1.21",
change to `"@kubrick/kubrickui": "^0.1.25"`

2021-08-03 23:33 UTC, monkemedia commented on plugins/apolloConfig.js
> +  const link = onError(({ graphQLErrors }) => {
What does `link` mean?

2021-08-03 23:33 UTC, monkemedia commented on graphql/mutations/readNotification.gql
> +}
Maybe we should add eslint for GraphQL

2021-08-04 11:00 UTC, EmmaBaldachin commented on package.json
> +    "@kubrick/kubrickui": "^0.1.21",
done

2021-08-04 11:02 UTC, EmmaBaldachin commented on plugins/apolloConfig.js
> +  const link = onError(({ graphQLErrors }) => {
it's just the default name for what the error handler expects at the bottom, i.e: 
 return {
    httpEndpoint: MOCKED_ENDPOINT,
    link...

rather than link: anAlias

2021-08-04 11:12 UTC, monkemedia approved these changes

2021-08-04 11:24 UTC, merged